"""empty message

Revision ID: 430a335bb0d2
Revises: 558258b65fb3
Create Date: 2021-11-21 18:48:28.747880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430a335bb0d2'
down_revision = '558258b65fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
