"""empty message

Revision ID: 558258b65fb3
Revises: 
Create Date: 2021-11-21 18:46:33.474827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558258b65fb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pdf_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('policy_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pdf_data_pkey')
    )
    op.drop_table('products')
    # ### end Alembic commands ###
